boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exceptions.o: exceptions.c exceptions.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_setup.o: idt_setup.c idt_setup.h x86_desc.h types.h exceptions.h \
  lib.h rtc.h keyboard.h i8259.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h keyboard.h rtc.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h
lib.o: lib.c lib.h types.h
rtc.o: rtc.c rtc.h i8259.h types.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
